//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace competition.HavaDurumuServis {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HavaDurumuServis.HavaDurumuSoap")]
    public interface HavaDurumuSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHavaDurumu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        competition.HavaDurumuServis.ForeCast[] GetHavaDurumu(string user, string password, string bolgeID, string culture);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHavaDurumu", ReplyAction="*")]
        System.Threading.Tasks.Task<competition.HavaDurumuServis.ForeCast[]> GetHavaDurumuAsync(string user, string password, string bolgeID, string culture);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ForeCast : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int forecastIDField;
        
        private string bolgeField;
        
        private string enYuksekSicaklikField;
        
        private string enDusukSicaklikField;
        
        private string iconField;
        
        private string nemField;
        
        private string ruzgarField;
        
        private string durumTextField;
        
        private System.DateTime tarihField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ForecastID {
            get {
                return this.forecastIDField;
            }
            set {
                this.forecastIDField = value;
                this.RaisePropertyChanged("ForecastID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Bolge {
            get {
                return this.bolgeField;
            }
            set {
                this.bolgeField = value;
                this.RaisePropertyChanged("Bolge");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EnYuksekSicaklik {
            get {
                return this.enYuksekSicaklikField;
            }
            set {
                this.enYuksekSicaklikField = value;
                this.RaisePropertyChanged("EnYuksekSicaklik");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EnDusukSicaklik {
            get {
                return this.enDusukSicaklikField;
            }
            set {
                this.enDusukSicaklikField = value;
                this.RaisePropertyChanged("EnDusukSicaklik");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Icon {
            get {
                return this.iconField;
            }
            set {
                this.iconField = value;
                this.RaisePropertyChanged("Icon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nem {
            get {
                return this.nemField;
            }
            set {
                this.nemField = value;
                this.RaisePropertyChanged("Nem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Ruzgar {
            get {
                return this.ruzgarField;
            }
            set {
                this.ruzgarField = value;
                this.RaisePropertyChanged("Ruzgar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DurumText {
            get {
                return this.durumTextField;
            }
            set {
                this.durumTextField = value;
                this.RaisePropertyChanged("DurumText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime Tarih {
            get {
                return this.tarihField;
            }
            set {
                this.tarihField = value;
                this.RaisePropertyChanged("Tarih");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HavaDurumuSoapChannel : competition.HavaDurumuServis.HavaDurumuSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HavaDurumuSoapClient : System.ServiceModel.ClientBase<competition.HavaDurumuServis.HavaDurumuSoap>, competition.HavaDurumuServis.HavaDurumuSoap {
        
        public HavaDurumuSoapClient() {
        }
        
        public HavaDurumuSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HavaDurumuSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HavaDurumuSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HavaDurumuSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public competition.HavaDurumuServis.ForeCast[] GetHavaDurumu(string user, string password, string bolgeID, string culture) {
            return base.Channel.GetHavaDurumu(user, password, bolgeID, culture);
        }
        
        public System.Threading.Tasks.Task<competition.HavaDurumuServis.ForeCast[]> GetHavaDurumuAsync(string user, string password, string bolgeID, string culture) {
            return base.Channel.GetHavaDurumuAsync(user, password, bolgeID, culture);
        }
    }
}
